#!/usr/bin/python
import ast
import json
import sys
import requests
from constants import *


# TO-DO add function to verify that the amount of arguments is valid for every function case


if __name__ == '__main__':

    function = sys.argv[1]
    if function == ADD_TASK:
        task_name = sys.argv[2]
        r = requests.post(ADD_TASK_URL, data=task_name.encode('utf-8'))

    elif function == UPDATE_TASK:
        old_task, updated_task = sys.argv[2], sys.argv[3]
        tasks_data = {OLD_TASK: old_task, UPDATED_TASK: updated_task}
        requests.post(UPDATE_TASK_URL, data=json.dumps(tasks_data))

    elif function == LIST_TASKS or function == LIST_COMPLETED_TASKS:
        res = requests.get(GET_LIST_TASKS_COMMAND + function)
        print(ast.literal_eval(res.text)[TABLE_OUTPUT])

    elif function == COMPLETE_TASK or function == UNDO_TASK:
        task_name = sys.argv[2]
        tasks_data = {TASK_NAME: task_name, TASK_STATUS: function}
        r = requests.post(CHANGE_TASK_STATE_URL, data=json.dumps(tasks_data))

    elif function == DELETE_TASK:
        task_name = sys.argv[2]
        res = requests.post(DELETE_TASK_URL, data=task_name.encode('utf-8'))
        res = ast.literal_eval(res.text)
        if ERROR in res: print(DELETE_ERROR+ task_name +" , "+ TASK_NOT_FOUND)
    else:
        print(UNKNOWN_COMMAND)
